In [1]:
import pandas as pd

In [4]:
data = pd.read_excel("mock-data.xlsx")
data

   olympic/paralympic sport discipline genre  viability  competitiveness
0             olympic    AL         SL     M  42.785810        54.518146
1             olympic    AL         GS     M   8.828903        14.325461
2             olympic    AL         SG     M  83.488496        72.563035
3             olympic    AL         DH     M  84.247847        96.261337
4             olympic    AL         AC     M  52.805326        58.288498
5             olympic    SB        SBX     M  63.103216         9.500847
6             olympic    SB         HP     M  88.911614        60.253876
7             olympic    SB        SBS     M   3.308445        55.065757
8             olympic    SB        PAR     M  77.070603        45.947063
9             olympic    FS         SX     M  32.676877        63.434030
10            olympic    FS         HP     M  82.346686         9.921178
11            olympic    FS         SS     M   1.180970         8.850662
12            olympic    FS         MO     M  40.342991        17.489796
13            olympic    FS         AE     M  76.023535        62.898331
14            olympic    NC         NC     M   9.586027        25.040073
15            olympic    SJ         SJ     M  40.977322        46.593342
16            olympic    CC         CC     M  88.793957        38.263186
17            olympic    BT         BT     M  94.986786        62.713567
18            olympic    AL         SL     F  66.005281        53.747207
19            olympic    AL         GS     F  16.911804        71.809741
20            olympic    AL         SG     F  77.663086         5.238409
21            olympic    AL         DH     F  60.154282        56.559751
22            olympic    AL         AC     F  62.341696        76.587801
23            olympic    SB        SBX     F  41.600785        92.413794
24            olympic    SB         HP     F   9.275140        54.648454
25            olympic    SB        SBS     F   8.194929        48.706718
26            olympic    SB        PAR     F  67.099674        83.542132
27            olympic    FS         SX     F  96.897710        63.122931
28            olympic    FS         HP     F  38.799029        71.150575
29            olympic    FS         SS     F  33.112610        26.002501
30            olympic    FS         MO     F  98.657872        91.577662
31            olympic    FS         AE     F  64.558030        95.786333
32            olympic    NC         NC     F  46.181422        64.945984
33            olympic    SJ         SJ     F  76.928010        71.714334
34            olympic    CC         CC     F  67.173065        76.460792
35            olympic    BT         BT     F  48.631971         2.312725

In [5]:
data.to_csv("mock-data.csv")